name: "alex's notes"
description: online notebook of Alex Levine
meta_description: "alex levine's notebook"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-53669222-1'

# Details for the RSS feed generator
url:            'blog url'
author:         'Alex Levine'
author_description: 'Alex writes about tech, programming, startups, food, and travel.'