name: "Alex Levine"
description: "web developer // austin, tx"
meta_description: "alex levine's notebook"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.alevee.me'
google_analytics: 'UA-53669222-1'

# Details for the RSS feed generator
url:            'blog url'
author:         'Alex Levine'
author_description: 'Web developer living in Austin, Texas. Lead developer for vThreat. I write about life, tech, business, food, and travel.'