name: "Alex Levine"
title: 'Alex Levine - Web Developer in Austin, Texas'
description: "web developer // austin, tx"
meta_description: "alex levine's blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://alevee.me'
google_analytics: 'UA-53669222-1'
permalink: pretty

# Facebook Open Graph
facebook_profile_url: 'https://www.facebook.com/alexlevine'

# Details for the RSS feed generator
url:            'http://alevee.me'
author:         'Alex Levine'
author_description: 'Web developer living in Austin, Texas. Lead Engineer at Ticketbud. I write about life, tech, business, food, and travel.'
